volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/jsekne/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/jsekne/data/mariadb
                        o: bind
                        type: none

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements
      dockerfile: ./nginx/Dockerfile
      args:
        - DOMAIN=${DOMAIN}
        - CERTS_=${CERTS_}
    ports:
      - "443:443"
      - "81:81"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - DB_ROOT_USER=${DB_ROOT_USER}
      - DB_ROOT_PWD=${DB_ROOT_PWD}
    env_file:
      - .env
    networks:
      - inception
    restart: always
  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - inception
    restart: always
